name: Bug report
description: Create a report to help us improve WhisperX
title: "[Bug] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: When I press the hotkey...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Open WhisperX
        2. Press the hotkey to start recording
        3. Release the hotkey
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Video
      description: Please add screenshots or a screen recording to help explain your problem.
  - type: input
    id: macos-version
    attributes:
      label: macOS Version
      placeholder: e.g. macOS 15.2 Sequoia
    validations:
      required: true
  - type: input
    id: mac-model
    attributes:
      label: Mac Model
      placeholder: e.g. MacBook Pro M3, Mac Mini M2
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: WhisperX Version
      placeholder: e.g. 1.0.0
    validations:
      required: true
  - type: dropdown
    id: whisper-model
    attributes:
      label: Whisper Model
      description: Which Whisper model are you using?
      options:
        - tiny
        - base
        - small
        - medium
        - large
        - "Don't know / Not applicable"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / Error Messages
      description: Paste any relevant logs from Console.app here (filter by "whisperX").
      render: text
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here (e.g., audio device being used, hotkey configuration).
